language: java
jdk:
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Use latest JDK
addons:
    apt:
        packages:
            - oracle-java8-installer
